repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        always_run: true
      - id: clippy
        always_run: true
      - id: cargo-check
        always_run: true
  - repo: local
    hooks:
      - id: test
        name: cargo test
        entry: cargo test --workspace
        language: system
        always_run: true
        pass_filenames: false
      - id: line count
        name: line count
        entry: ./line_count.sh
        language: system
        always_run: true
        pass_filenames: false
