[package]
name = "tinytrace"
version = "0.1.0"
edition = "2021"

[[test]]
name = "integration"
path = "test/test.rs"

[dependencies]
glam = "0.23.0"
ash = "0.38.0+1.3.281"
thiserror = "1.0.59"

[dev-dependencies]
smallpt = "0.4.2"